/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Native Magic Wormhole client for Electron */
export declare class WormholeClient {
  /** Create a new WormholeClient instance */
  constructor()
  /**
   * Generate a wormhole code for sending a file
   * Returns the code immediately after connecting to the mailbox server.
   * The actual PAKE exchange happens when sendFile() is called.
   */
  createSendCode(codeLength?: number | undefined | null): Promise<string>
  /**
   * Send a file after code has been generated
   * This connects to the receiver (PAKE exchange) and then sends the file.
   * The progress callback receives ProgressEvent updates.
   */
  sendFile(filePath: string, progressCallback: (err: null | Error, progress: ProgressEvent) => void): Promise<void>
  /**
   * Connect to receive a file using the given code
   * Returns information about the offered file
   */
  connectReceive(code: string): Promise<ReceiveOffer>
  /**
   * Accept the incoming file transfer
   * Returns the path to the saved file
   */
  acceptTransfer(outputDir: string, progressCallback: (err: null | Error, progress: ProgressEvent) => void): Promise<string>
  /** Reject the incoming file transfer */
  rejectTransfer(): Promise<void>
  /** Cancel any active operation */
  cancel(): void
}

/** Add two numbers - basic async test */
export declare function add(a: number, b: number): Promise<number>

/** Get version string */
export declare function getVersion(): string

/** Hello world test function to verify napi-rs setup */
export declare function hello(): string

/** Progress information for file transfers */
export interface ProgressEvent {
  /** Bytes transferred so far */
  transferred: number
  /** Total bytes to transfer */
  total: number
  /** Percentage complete (0-100) */
  percent: number
}

/** Information about an incoming file transfer offer */
export interface ReceiveOffer {
  /** Name of the file being sent */
  filename: string
  /** Size of the file in bytes */
  filesize: number
}
